<?php

namespace AppBundle\Repository;

/**
 * RandomChatPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RandomChatPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
