<?php

namespace AppBundle\Repository\Security;

/**
 * QuestionCatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCatalogueRepository extends \Doctrine\ORM\EntityRepository
{
}
